### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Khorneflakes1** [6fears7/Voidcrid-Modding#12]
You don't have an issue page for https://thunderstore.io/package/Voidcrid/AcridM1BitePlus, so I'm posting this issue here.  https://thunderstore.io/package/TheMysticSword/MysticsRisky2Utils causes m1biteplus to cease functioning. It just doesn't even load, not even the config file. It seems to remove something vital to m1biteplus' operation. I have the log file, if you want to read it, but the parts related to m1biteplus are so short that I can just post them here right now. 

[Info   :   BepInEx] TS Manifest: Voidcrid-AcridM1BitePlus-1.1.0
[Info   :   BepInEx] Loading [M1BitePlus 1.1.0]
[Warning: Unity Log] AddComponent asking for invalid type

and then a ways down below that:

[Debug  :     R2API] Hook removed by assembly: Voidcrid.dll for: RoR2.HealthComponent+AssetReferences.Resolve
[Error  :     R2API] Exception in ScanPluginsForNetworkCompat while scanning plugin com.sixfears7.M1BitePlus
[Error  :     R2API] R2API Failed to properly scan the assembly.
Please make sure you are compiling against net standard 2.0 and not anything else when making a plugin for Risk of Rain 2 !
System.NullReferenceException: Object reference not set to an instance of an object
  at R2API.Utils.NetworkCompatibilityHandler.ScanPluginsForNetworkCompat (System.Object _, System.EventArgs __) [0x00086] in <2c534cf27cc8448ea6ef44ae40b57af1>:IL_0086 
  
 Even that might've been too much. Again, just tell me to and I'll send you the full log in a little while(I'm not really in the position to right this instant). I haven't contacted TheMysticSword about this yet, but I can send him an issue report about this too if he's the one who needs to do the work.
 
 Your mod is really handy for giving acrid a ranged M1, so it's a shame that this isn't compatible with mystic's mods as a result of this.

**Comment by 6fears7** [comment]
Hey @Khorneflakes1 thanks for the heads up. That repo had been rebased so I probably janked something up in the process. I'll take a look and add a github for Bite too just to have it. 

Thanks!

**Comment by 6fears7** [comment]
@Khorneflakes1 may post a response as to what the _real_ mod culprit is affecting Bite, as testing with a separate profile resolves the issue.
