### ISSUE TITLE
SOULR?OT debuff's special effects problem

### ISSUE THREAD

**Issue by BTP-G** [6fears7/Voidcrid-Modding#13]
**SOULR?OT debuff effects will make the game frame rate greatly reduced, please can you improve it？**

**Comment by 6fears7** [comment]
Hey @BTP-G, thanks for reaching out. 

Unfortunately, I am not the creator of Deeprot / Soulrot. I just modded Voidcrid to use that debuff on Void abilities when equipped. 

I don’t think that Spikestrip 2.0 has a GitHub repo to post issues to, but they do have a discord where you could  post a log when it starts killing framerate for the creator to debug. 

Hope this helps,
