### ISSUE TITLE
[Suggestion] Skin-only version?

### ISSUE THREAD

**Issue by SerialDreams** [6fears7/Voidcrid-Modding#15]
Would be a nice to have for client-side friendliness.

**Comment by 6fears7** [comment]
I noticed you uploaded a Skins-Only version. Is there anything additional you’re looking for regarding this request or is this resolved?

**Comment by 6fears7** [comment]
Closing as resolved with release: https://thunderstore.io/package/ReSerial/Voidcrid_Skins/
