### ISSUE TITLE
Flamebreath Autofire & Balance 

### ISSUE THREAD

**Issue by BungoDungo** [6fears7/Voidcrid-Modding#9]
Speaking for a friend who plays my server's modpack that is currently running Voidcrid.

Firebreath is a very good skill, but it's kind of annoying to mash the atttack button, and he suggests just having it immediately start firing again as long as left click is held down.

Additionally the jail chance is kind of high in the vanilla settings. This isn't as big of an issue as it is configurable, but does lead to Acrid being significantly stronger than other survivors without tinkering in the .cfg

**Comment by 6fears7** [comment]
Thanks for the feedback, @BungoDungo ! 

I am heavily considering swapping the jailing mechanic from "instant kill" to "tether" _a la_ Tentabauble, and will also determine if the default config values should be altered. I will also test re-activating Flamebreath on hold.

Thanks for reaching out

**Comment by BungoDungo** [comment]
Sure thing, I'm glad to help. I quite like this mod as well, acrid is soo fun. 

Tethering sounds like a cool idea

**Comment by 6fears7** [comment]
Resolved in #10
